In [1]:
import pandas as pd
d=pd.read_csv("fitness_tracker_dataset.csv")
d=d.head(1000)
d

,user_id,date,steps,calories_burned,distance_km,active_minutes,sleep_hours,heart_rate_avg,workout_type,weather_conditions,location,mood
0,468,2023-01-01,4530,2543.02,16.10,613,1.5,176,Walking,Clear,Park,Tired
1,879,2023-01-01,11613,1720.76,8.10,352,6.3,128,Cycling,Fog,Park,Happy
2,152,2023-01-01,27335,1706.35,3.57,236,6.7,134,Yoga,Snow,Park,Neutral
3,311,2023-01-01,13459,2912.38,6.41,1329,11.6,116,Swimming,Rain,Office,Tired
4,759,2023-01-01,15378,3344.51,17.88,52,7.4,84,Swimming,Rain,Office,Neutral
...,...,...,...,...,...,...,...,...,...,...,...,...
995,518,2023-01-01,19783,3257.98,4.22,964,8.7,68,Cycling,Snow,Home,Stressed
996,801,2023-01-01,2982,2486.78,0.57,567,0.9,149,Gym Workout,Clear,Park,Stressed
997,330,2023-01-01,29777,3009.25,4.88,167,12.0,173,Gym Workout,Snow,Other,Stressed
998,390,2023-01-01,1618,1813.25,14.34,1315,10.1,168,Cycling,Clear,Park,Neutral
999,658,2023-01-01,20875,2171.01,16.63,712,10.4,90,Cycling,Rain,Office,Tired

In [4]:
d1=d.select_dtypes(["int64","float64"])
d1

,user_id,steps,calories_burned,distance_km,active_minutes,sleep_hours,heart_rate_avg
0,468,4530,2543.02,16.10,613,1.5,176
1,879,11613,1720.76,8.10,352,6.3,128
2,152,27335,1706.35,3.57,236,6.7,134
3,311,13459,2912.38,6.41,1329,11.6,116
4,759,15378,3344.51,17.88,52,7.4,84
...,...,...,...,...,...,...,...
995,518,19783,3257.98,4.22,964,8.7,68
996,801,2982,2486.78,0.57,567,0.9,149
997,330,29777,3009.25,4.88,167,12.0,173
998,390,1618,1813.25,14.34,1315,10.1,168
999,658,20875,2171.01,16.63,712,10.4,90

In [5]:
d1.corr()

,user_id,steps,calories_burned,distance_km,active_minutes,sleep_hours,heart_rate_avg
user_id,1.000000,-0.019224,-0.004409,0.034479,-0.014787,0.023234,0.003641
steps,-0.019224,1.000000,-0.024129,-0.020063,-0.014623,-0.006250,0.016091
calories_burned,-0.004409,-0.024129,1.000000,0.010207,-0.034388,0.014072,-0.020229
distance_km,0.034479,-0.020063,0.010207,1.000000,-0.020714,-0.022710,0.050204
active_minutes,-0.014787,-0.014623,-0.034388,-0.020714,1.000000,0.038941,-0.013041
sleep_hours,0.023234,-0.006250,0.014072,-0.022710,0.038941,1.000000,-0.001399
heart_rate_avg,0.003641,0.016091,-0.020229,0.050204,-0.013041,-0.001399,1.000000

In [7]:
x=d1[["steps","distance_km"]]
y=d1["calories_burned"]

In [8]:
d1.kurt()

user_id           -1.136810
steps             -1.111950
calories_burned   -1.214293
distance_km       -1.180295
active_minutes    -1.199857
sleep_hours       -1.237119
heart_rate_avg    -1.245246
dtype: float64

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)
x_train

     steps  distance_km
29    4798        11.42
535   1457         9.11
695  14384        18.82
557  22925        18.35
836  18522        18.44
..     ...          ...
106  15022         6.25
270   8838        19.99
860  11418        12.05
435  20566         9.41
102  16030        11.26

[800 rows x 2 columns]

In [12]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [15]:
lr.fit(x_train,y_train)

LinearRegression()

In [17]:
y1=lr.predict(x_test)
y1

array([2764.33447202, 2758.84295768, 2767.49736681, 2737.38417006,
       2734.11362657, 2790.09065464, 2747.80482512, 2728.86211831,
       2736.90064341, 2787.24200886, 2742.73718796, 2729.4357401 ,
       2729.17913806, 2771.71824956, 2747.05171766, 2771.10096282,
       2770.91186197, 2770.54751656, 2759.66166142, 2783.06188325,
       2741.38966586, 2779.53767147, 2761.84177424, 2747.83756385,
       2748.73637   , 2732.89155561, 2785.6209291 , 2733.8605299 ,
       2791.04462829, 2752.22237719, 2746.52072393, 2784.94601258,
       2786.47316432, 2732.66541754, 2739.81434822, 2784.92754093,
       2789.25109227, 2775.58896446, 2736.56061669, 2789.3411019 ,
       2728.80446183, 2785.23432379, 2774.87381307, 2748.86598476,
       2739.31530707, 2743.01539752, 2761.87692702, 2769.51935151,
       2738.53662329, 2727.26995505, 2763.02438224, 2780.96462896,
       2760.39244171, 2723.18000463, 2783.55822491, 2738.46608235,
       2743.95165243, 2766.01901215, 2767.30984997, 2760.71145227,
       2745.45113727, 2765.71975756, 2730.23047638, 2761.92466092,
       2755.59483747, 2738.49103041, 2747.93320709, 2742.95609709,
       2728.22859303, 2775.8108852 , 2758.78702887, 2776.00861883,
       2765.62723375, 2761.32574313, 2766.54118855, 2740.24020377,
       2755.19386127, 2731.98100423, 2774.60572564, 2748.92258789,
       2734.55645491, 2786.64522112, 2755.262028  , 2739.69112068,
       2784.45133678, 2779.78177718, 2787.96895557, 2789.06750697,
       2764.11545908, 2753.24566521, 2760.22335376, 2739.04649524,
       2733.78503736, 2730.67374513, 2732.04866513, 2746.51403516,
       2759.3888245 , 2781.05611369, 2769.00795219, 2764.65046512,
       2775.1875906 , 2752.56153734, 2728.12426293, 2762.33062126,
       2741.83525473, 2775.36843404, 2745.92066654, 2728.31411048,
       2762.08494871, 2772.45410316, 2754.72638456, 2736.64457389,
       2781.55861233, 2784.98791625, 2762.68968832, 2729.38238467,
       2731.41932029, 2734.92045713, 2772.91402564, 2742.85572303,
       2744.40820038, 2764.59127435, 2778.20593653, 2760.98691155,
       2781.35310154, 2767.28555979, 2784.81210007, 2728.4150569 ,
       2775.33437333, 2741.47723076, 2733.27380398, 2781.682963  ,
       2772.05100494, 2745.08587961, 2781.08151678, 2752.79299944,
       2730.42317397, 2754.55453427, 2762.92958036, 2736.35660806,
       2778.51274826, 2766.15224924, 2759.97920418, 2768.97309581,
       2757.27645518, 2745.13010887, 2736.28892705, 2741.93606154,
       2781.85255422, 2790.3111657 , 2734.35084472, 2772.51839538,
       2734.36384247, 2787.68250797, 2745.06448005, 2732.05697738,
       2758.93390333, 2739.88137465, 2728.12504983, 2777.22251386,
       2760.55935429, 2755.56931451, 2742.45034526, 2772.95966969,
       2737.41924573, 2787.07858521, 2764.46113036, 2751.52807602,
       2766.1484672 , 2790.24488852, 2768.40533604, 2764.58604461,
       2747.47626112, 2758.97786504, 2775.67606666, 2745.30460344,
       2734.70531067, 2754.38706944, 2781.54290814, 2745.1562484 ,
       2744.00031283, 2778.58381477, 2729.96555917, 2744.3509474 ,
       2773.0510773 , 2753.69778128, 2750.4642805 , 2764.76249856,
       2768.84331256, 2738.11368943, 2786.62783898, 2760.4634746 ,
       2744.06625559, 2768.08701771, 2753.35496116, 2754.99612435,
       2755.63126873, 2748.73811373, 2768.01859915, 2774.58295954])

In [18]:
from sklearn.metrics import r2_score

In [21]:
r2_score(y_test,y1)

1.6642172153580326e-05

In [ ]:
#visualization
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
fig=plt.figure()
ax=fig.add_subplot(111,projection="3d")
ax.scatter(x["TV"],x["Radio"],y)